version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ~/.docker/cli-plugins:/var/jenkins_home/.docker/cli-plugins
      - ~/.docker/buildx:/var/jenkins_home/.docker/buildx

volumes:
  jenkins_home:
    external: true
    name: jenkins_home
